// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// armadilloVersion
Rcpp::List armadilloVersion();
RcppExport SEXP _RcppDEpar_armadilloVersion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(armadilloVersion());
    return rcpp_result_gen;
END_RCPP
}
// DEoptim_impl
Rcpp::List DEoptim_impl(const arma::colvec& minbound, const arma::colvec& maxbound, SEXP fnS, const Rcpp::List& control, SEXP rhoS);
RcppExport SEXP _RcppDEpar_DEoptim_impl(SEXP minboundSEXP, SEXP maxboundSEXP, SEXP fnSSEXP, SEXP controlSEXP, SEXP rhoSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type minbound(minboundSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type maxbound(maxboundSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fnS(fnSSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhoS(rhoSSEXP);
    rcpp_result_gen = Rcpp::wrap(DEoptim_impl(minbound, maxbound, fnS, control, rhoS));
    return rcpp_result_gen;
END_RCPP
}
// putFunPtrInXPtr
SEXP putFunPtrInXPtr(const std::string& fstr);
RcppExport SEXP _RcppDEpar_putFunPtrInXPtr(SEXP fstrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fstr(fstrSEXP);
    rcpp_result_gen = Rcpp::wrap(putFunPtrInXPtr(fstr));
    return rcpp_result_gen;
END_RCPP
}
// putFunPtrInXPtrRaw
SEXP putFunPtrInXPtrRaw(const std::string& fstr, long throw_after);
RcppExport SEXP _RcppDEpar_putFunPtrInXPtrRaw(SEXP fstrSEXP, SEXP throw_afterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fstr(fstrSEXP);
    Rcpp::traits::input_parameter< long >::type throw_after(throw_afterSEXP);
    rcpp_result_gen = Rcpp::wrap(putFunPtrInXPtrRaw(fstr, throw_after));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppDEpar_armadilloVersion", (DL_FUNC) &_RcppDEpar_armadilloVersion, 0},
    {"_RcppDEpar_DEoptim_impl", (DL_FUNC) &_RcppDEpar_DEoptim_impl, 5},
    {"_RcppDEpar_putFunPtrInXPtr", (DL_FUNC) &_RcppDEpar_putFunPtrInXPtr, 1},
    {"_RcppDEpar_putFunPtrInXPtrRaw", (DL_FUNC) &_RcppDEpar_putFunPtrInXPtrRaw, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppDEpar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
